review commit
MunteanuM/my_cinema_app pull request #3
Opened 2022-08-02 11:39 UTC by MunteanuM

Email registration new along the other trello tickets

2022-08-02 11:40 UTC, MunteanuM commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BE] Check email address before creating an account](https://trello.com/c/NNx2bWZi/10-be-check-email-address-before-creating-an-account)

2022-08-02 19:33 UTC, maxinasa commented
Please remove the .pyc files from the repo and add them in the gitignore file.

2022-08-02 19:53 UTC, maxinasa approved these changes

2022-08-02 19:53 UTC, maxinasa commented on app_users/forms.py
> +            ]
Please, use the pyflake or pylint to check your code before committing. For example, here, there is no newline at the end of the file.

2022-08-02 19:53 UTC, maxinasa commented on app_users/token.py
> +account_activation_token = AccountActivationTokenGenerator()
One of these two files is a duplicate, right?

2022-08-02 19:53 UTC, maxinasa commented on app_users/urls.py
> +    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
Although it's easier to search and match, it's recommended to use hyphens in URIs.

2022-08-06 08:11 UTC, drejleeo requested changes
Again, remove `.pyc` files

2022-08-06 08:11 UTC, drejleeo commented on basepage/templates/basepage/base.html
> +    <a href="{% url 'signup' %}">register</a>
On the other PR I said something about using relative path. I meant this. This is the django way of referencing internal paths. These tags `{% something %}` are called template tags. The url template tag solves url referenced by their path names using a reverse. You can even configure your own template tags. You can give it a read on the documentation if you are curious.

2022-08-11 10:29 UTC, closed without merging