Daily uploads
MunteanuM/my_cinema_app pull request #4
Opened 2022-08-04 08:38 UTC by MunteanuM

Add possibility to import Movies

2022-08-04 08:49 UTC, maxinasa commented on basepage/views.py
> +    file = r'C:\Users\mihamunteanu\DjangoProjects\cinema\imdb_top_1000.csv'
This is definitely not ok with the hardcoded path.

2022-08-04 08:49 UTC, maxinasa commented on app_users/forms.py
> +            ]
I'm not exactly sure, but I feel like a lot of these changes have already been present in a different PR.

2022-08-06 08:04 UTC, drejleeo requested changes
Add `.pyc` files to `.gitignore` and delete them, otherwise they'll remain on git.

2022-08-06 08:04 UTC, drejleeo commented on app_users/templates/authentication/login.html
> -<a href="http://127.0.0.1:8000/login/">Sign up</a>
Don't reference the entire url. Use relative paths

2022-08-09 09:22 UTC, closed without merging